config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_bash_completion:
    src: bash_completion
    dst: ~/.bash_completion
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
profiles:
  trout91:
    dotfiles:
    - f_bash_completion
    - f_bash_aliases
